import Card from "../types/cardList";

const cardList: Card[] = [
    {
        id: -1,
        name: 'MAINbackside',
        imageUrl: '/backside/MAIN.jpg',
        cardName: "backsideMAIN",
        cardType: "",
        cardColor: [""],
        cardText: "",
        cardEffectConst: "",
        cardEffectAuto: "",
        cardEffectEnter: "",
        cardEffectAction: "",
        cardLevel: 0,
        cardCost: 0,
        cardGrowCost: 0,
        cardLimit: 0,
        cardLRIGType: "",
        cardTeamName: "",
        cardClass: "",
        cardPower: 0,
        cardBurst: "",
        cardUseTime: [""],
        isLRIGCenter: false,
        isLRIGSupport: false,
        cardEffect: [""],
        isDown: false,
        isFreeze: false,
        statusName: ""
    },
    {
        id: 0,
        name: 'LRIGbackside',
        imageUrl: '/backside/LRIG.jpg',
        cardName: "backsideLRIG",
        cardType: "",
        cardColor: [""],
        cardText: "",
        cardEffectConst: "",
        cardEffectAuto: "",
        cardEffectEnter: "",
        cardEffectAction: "",
        cardLevel: 0,
        cardCost: 0,
        cardGrowCost: 0,
        cardLimit: 0,
        cardLRIGType: "",
        cardTeamName: "",
        cardClass: "",
        cardPower: 0,
        cardBurst: "",
        cardUseTime: [""],
        isLRIGCenter: false,
        isLRIGSupport: false,
        cardEffect: [""],
        isDown: false,
        isFreeze: false,
        statusName: ""
    },
    {
        id: 1,
        name: 'WXDi-D01-001[EN]',
        imageUrl: '/WXDi-D01/LRIG/WXDi-D01-001[EN].jpg',
        cardName: "At =Noll=, the Opened Gate",
        cardType: "LRIG",
        cardColor: ["green"],
        cardText: "",
        cardEffectConst: "",
        cardEffectAuto: "",
        cardEffectEnter: "",
        cardEffectAction: "",
        cardLevel: 0,
        cardCost: 0,
        cardGrowCost: 0,
        cardLimit: 0,
        cardLRIGType: "At",
        cardTeamName: "owata",
        cardClass: "",
        cardPower: 0,
        cardBurst: "",
        cardUseTime: [""],
        isLRIGCenter: true,
        isLRIGSupport: false,
        cardEffect: [""],
        isDown: false,
        isFreeze: false,
        statusName: ""
    },
    {
        id: 2,
        name: 'WXDi-D01-002[EN]',
        imageUrl: '/WXDi-D01/LRIG/WXDi-D01-002[EN].jpg',
        cardName: "At =Ett=, the Opened Gate",
        cardType: "LRIG",
        cardColor: ["green"],
        cardText: "",
        cardEffectConst: "",
        cardEffectAuto: "",
        cardEffectEnter: "",
        cardEffectAction: "",
        cardLevel: 1,
        cardCost: 0,
        cardGrowCost: 0,
        cardLimit: 2,
        cardLRIGType: "At",
        cardTeamName: "Ancient Surprise",
        cardClass: "",
        cardPower: 0,
        cardBurst: "",
        cardUseTime: [""],
        isLRIGCenter: true,
        isLRIGSupport: false,
        cardEffect: [""],
        isDown: false,
        isFreeze: false,
        statusName: ""
    },
    {
        id: 3,
        name: 'WXDi-D01-003[EN]',
        imageUrl: '/WXDi-D01/LRIG/WXDi-D01-003[EN].jpg',
        cardName: "At =Tva=, the Opened Gate",
        cardType: "LRIG",
        cardColor: ["green"],
        cardText: "",
        cardEffectConst: "",
        cardEffectAuto: "",
        cardEffectEnter: "",
        cardEffectAction: "",
        cardLevel: 2,
        cardCost: 0,
        cardGrowCost: 1,
        cardLimit: 5,
        cardLRIGType: "At",
        cardTeamName: "Ancient Surprise",
        cardClass: "",
        cardPower: 0,
        cardBurst: "",
        cardUseTime: [""],
        isLRIGCenter: true,
        isLRIGSupport: false,
        cardEffect: [""],
        isDown: false,
        isFreeze: false,
        statusName: ""
    },
    {
        id: 4,
        name: 'WXDi-D01-004[EN]',
        imageUrl: '/WXDi-D01/LRIG/WXDi-D01-004[EN].jpg',
        cardName: "At =Tre=, the Opened Gate",
        cardType: "LRIG",
        cardColor: ["green"],
        cardText: "",
        cardEffectConst: "",
        cardEffectAuto: "",
        cardEffectEnter: "Nhóm <Ancient Surprise>: Vào Sân: [Nhập 2 lá bài]. Nếu các lá bài được đưa vào vùng nguyên liệu theo cách này mà không chung lớp với nhau thì thực hiện: [Nhập 1 lá bài].",
        cardEffectAction: "Nhóm <Ancient Surprise>: Hành Động(1 lần/lượt)(Tốn 0 nguyên liệu): Nếu 3 SIGNI trên sân của bạn có lớp khác nhau, tăng 3000 sức mạnh cho 3 SIGNI đó đến khi kết thúc lượt.",
        cardLevel: 3,
        cardCost: 0,
        cardGrowCost: 2,
        cardLimit: 6,
        cardLRIGType: "At",
        cardTeamName: "Ancient Surprise",
        cardClass: "",
        cardPower: 0,
        cardBurst: "",
        cardUseTime: [""],
        isLRIGCenter: true,
        isLRIGSupport: false,
        cardEffect: ["Action", "Enter"],
        isDown: false,
        isFreeze: false,
        statusName: ""
    },
    {
        id: 5,
        name: 'WXDi-D01-005[EN]',
        imageUrl: '/WXDi-D01/LRIG/WXDi-D01-005[EN].jpg',
        cardName: "",
        cardType: "LRIG",
        cardColor: ["red"],
        cardText: "",
        cardEffectConst: "",
        cardEffectAuto: "",
        cardEffectEnter: "",
        cardEffectAction: "",
        cardLevel: 0,
        cardCost: 0,
        cardGrowCost: 0,
        cardLimit: 0,
        cardLRIGType: "Tawil",
        cardTeamName: "Ancient Surprise",
        cardClass: "",
        cardPower: 0,
        cardBurst: "",
        cardUseTime: [""],
        isLRIGCenter: false,
        isLRIGSupport: true,
        cardEffect: [""],
        isDown: false,
        isFreeze: false,
        statusName: ""
    },
    {
        id: 6,
        name: 'WXDi-D01-006[EN]',
        imageUrl: '/WXDi-D01/LRIG/WXDi-D01-006[EN].jpg',
        cardName: "",
        cardType: "ASSIST LRIG",
        cardColor: ["red"],
        cardText: "",
        cardEffectConst: "",
        cardEffectAuto: "",
        cardEffectEnter: "Vào Sân: Chọn 1 SIGNI trên sân đối thủ với sức mạnh từ 8000 trở xuống và loại bỏ nó. Rút 1 lá bài và bỏ 1 lá bài.",
        cardEffectAction: "",
        cardLevel: 1,
        cardCost: 0,
        cardGrowCost: 0,
        cardLimit: 0,
        cardLRIGType: "Tawil",
        cardTeamName: "Ancient Surprise",
        cardClass: "",
        cardPower: 0,
        cardBurst: "",
        cardUseTime: ["Main Phase"],
        isLRIGCenter: false,
        isLRIGSupport: true,
        cardEffect: ["Enter"],
        isDown: false,
        isFreeze: false,
        statusName: ""
    },
    {
        id: 7,
        name: 'WXDi-D01-007[EN]',
        imageUrl: '/WXDi-D01/LRIG/WXDi-D01-007[EN].jpg',
        cardName: "",
        cardType: "ASSIST LRIG",
        cardColor: ["red"],
        cardText: "",
        cardEffectConst: "",
        cardEffectAuto: "",
        cardEffectEnter: "Vào Sân: Nếu có SIGNI màu đỏ trên sân của bạn, hãy loại bỏ 1 SIGNI trên sân của đối thủ với sức mạnh từ 10000 trở xuống. Nếu có SIGNI màu xanh dương trên sân của bạn, hãy rút 2 lá bài. Nếu có SIGNI màu xanh lá trên sân của bạn, [Nhập 2 lá bài].",
        cardEffectAction: "",
        cardLevel: 2,
        cardCost: 0,
        cardGrowCost: 1,
        cardLimit: 1,
        cardLRIGType: "Tawil",
        cardTeamName: "Ancient Surprise",
        cardClass: "",
        cardPower: 0,
        cardBurst: "",
        cardUseTime: ["Main Phase"],
        isLRIGCenter: false,
        isLRIGSupport: true,
        cardEffect: ["Enter"],
        isDown: false,
        isFreeze: false,
        statusName: ""
    },
    {
        id: 8,
        name: 'WXDi-D01-008[EN]',
        imageUrl: '/WXDi-D01/LRIG/WXDi-D01-008[EN].jpg',
        cardName: "",
        cardType: "LRIG",
        cardColor: ["blue"],
        cardText: "",
        cardEffectConst: "",
        cardEffectAuto: "",
        cardEffectEnter: "",
        cardEffectAction: "",
        cardLevel: 0,
        cardCost: 0,
        cardGrowCost: 0,
        cardLimit: 0,
        cardLRIGType: "Umr",
        cardTeamName: "Ancient Surprise",
        cardClass: "",
        cardPower: 0,
        cardBurst: "",
        cardUseTime: [""],
        isLRIGCenter: false,
        isLRIGSupport: true,
        cardEffect: [""],
        isDown: false,
        isFreeze: false,
        statusName: ""
    },
    {
        id: 9,
        name: 'WXDi-D01-009[EN]',
        imageUrl: '/WXDi-D01/LRIG/WXDi-D01-009[EN].jpg',
        cardName: "",
        cardType: "ASSIST LRIG",
        cardColor: ["blue"],
        cardText: "",
        cardEffectConst: "",
        cardEffectAuto: "",
        cardEffectEnter: "Vào Sân: Rút 2 lá bài.",
        cardEffectAction: "",
        cardLevel: 1,
        cardCost: 0,
        cardGrowCost: 0,
        cardLimit: 0,
        cardLRIGType: "Umr",
        cardTeamName: "Ancient Surprise",
        cardClass: "",
        cardPower: 0,
        cardBurst: "",
        cardUseTime: ["Main Phase"],
        isLRIGCenter: false,
        isLRIGSupport: true,
        cardEffect: ["Enter"],
        isDown: false,
        isFreeze: false,
        statusName: ""
    },
    {
        id: 10,
        name: 'WXDi-D01-010[EN]',
        imageUrl: '/WXDi-D01/LRIG/WXDi-D01-010[EN].jpg',
        cardName: "",
        cardType: "ASSIST LRIG",
        cardColor: ["blue"],
        cardText: "",
        cardEffectConst: "",
        cardEffectAuto: "",
        cardEffectEnter: "Vào Sân(Tốn 1 lá xanh dương và 1 lá màu bất kỳ): Hạ 1 SIGNI trên sân đối thủ.",
        cardEffectAction: "",
        cardLevel: 2,
        cardCost: 0,
        cardGrowCost: 1,
        cardLimit: 1,
        cardLRIGType: "Umr",
        cardTeamName: "Ancient Surprise",
        cardClass: "",
        cardPower: 0,
        cardBurst: "",
        cardUseTime: ["Main Phase", "Attack Phase"],
        isLRIGCenter: false,
        isLRIGSupport: true,
        cardEffect: ["Enter"],
        isDown: false,
        isFreeze: false,
        statusName: ""
    },
    {
        id: 11,
        name: 'WXDi-D01-011[EN]',
        imageUrl: '/WXDi-D01/LRIG/WXDi-D01-011[EN].jpg',
        cardName: "",
        cardType: "PIECE",
        cardColor: ["green", "red", "blue"],
        cardText: "Điều Kiện Sử Dụng: Có Nhóm <Ancient Surprise> trên sân với tất cả thành viên từ cấp 1 trở lên: Nhìn vào tám lá bài trên cùng của bộ bài của bạn. Đặt tối đa một SIGNI cấp 1, một SIGNI cấp 2 và một SIGNI cấp 3 trong số đó vào sân của bạn. Đặt phần còn lại ở dưới cùng của bộ bài của bạn theo thứ tự ngẫu nhiên. Sau đó, SIGNI cấp 1 đạt được 【Assassin】, SIGNI cấp 2 đạt được 【Double Crush】 và SIGNI cấp 3 đạt được 【Lancer】 cho đến khi kết thúc lượt.(Hiệu ứng vào sân của lá bài được đưa vào theo cách này sẽ không thể kích hoạt cho đến khi kết thúc lượt!).",
        cardEffectConst: "",
        cardEffectAuto: "",
        cardEffectEnter: "",
        cardEffectAction: "",
        cardLevel: 0,
        cardCost: 8,
        cardGrowCost: 0,
        cardLimit: 0,
        cardLRIGType: "",
        cardTeamName: "",
        cardClass: "",
        cardPower: 0,
        cardBurst: "",
        cardUseTime: ["Main Phase"],
        isLRIGCenter: false,
        isLRIGSupport: false,
        cardEffect: [""],
        isDown: false,
        isFreeze: false,
        statusName: ""
    },
    {
        id: 12,
        name: "WXDi-D01-012[EN]",
        imageUrl: "/WXDi-D01/MAIN/WXDi-D01-012[EN].jpg",
        cardName: "",
        cardType: "SIGNI",
        cardColor: ["green"],
        cardText: "",
        cardEffectConst: "Vĩnh Viễn: Miễn là có 3 hoặc nhiều lớp khác nhau giữa các SIGNI trong Vùng nguyên liệu của bạn, SIGNI này sẽ nhận được thêm 4000 sức tấn công.",
        cardEffectAuto: "",
        cardEffectEnter: "",
        cardEffectAction: "",
        cardLevel: 1,
        cardCost: 0,
        cardGrowCost: 0,
        cardLimit: 0,
        cardLRIGType: "",
        cardTeamName: "",
        cardClass: "Nature Tone: Cosmos",
        cardPower: 3000,
        cardBurst: "",
        cardUseTime: [""],
        isLRIGCenter: false,
        isLRIGSupport: false,
        cardEffect: ["Const"],
        isDown: false,
        isFreeze: false,
        statusName: ""
    },
    {
        id: 13,
        name: "WXDi-D01-013[EN]",
        imageUrl: "/WXDi-D01/MAIN/WXDi-D01-013[EN].jpg",
        cardName: "",
        cardType: "SIGNI",
        cardColor: ["green"],
        cardText: "",
        cardEffectConst: "",
        cardEffectAuto: "",
        cardEffectEnter: "",
        cardEffectAction: "",
        cardLevel: 2,
        cardCost: 0,
        cardGrowCost: 0,
        cardLimit: 0,
        cardLRIGType: "",
        cardTeamName: "",
        cardClass: "Idol Tone: Brave",
        cardPower: 10000,
        cardBurst: "[Nhập 3 lá bài]",
        cardUseTime: [""],
        isLRIGCenter: false,
        isLRIGSupport: false,
        cardEffect: [""],
        isDown: false,
        isFreeze: false,
        statusName: ""
    },
    {
        id: 14,
        name: "WXDi-D01-014[EN]",
        imageUrl: "/WXDi-D01/MAIN/WXDi-D01-014[EN].jpg",
        cardName: "",
        cardType: "SIGNI",
        cardColor: ["green"],
        cardText: "",
        cardEffectConst: "Vĩnh Viễn: Miễn là có ba hoặc nhiều lớp khác nhau giữa các SIGNI trong Vùng nguyên liệu của bạn, SIGNI này sẽ nhận được thêm 5000 sức mạnh.",
        cardEffectAuto: "",
        cardEffectEnter: "",
        cardEffectAction: "Hành Động(1 lần/lượt)(Tốn 2 lá bài xanh lá và 1 lá bài bất kỳ): Một SIGNI khác trên sân của bạn với sức mạnh từ 15000 trở lên sẽ nhận【Lancer】cho tới cuối lượt.",
        cardLevel: 2,
        cardCost: 0,
        cardGrowCost: 0,
        cardLimit: 0,
        cardLRIGType: "",
        cardTeamName: "",
        cardClass: "War Tone: Venom",
        cardPower: 3000,
        cardBurst: "",
        cardUseTime: [""],
        isLRIGCenter: false,
        isLRIGSupport: false,
        cardEffect: ["Const", "Action"],
        isDown: false,
        isFreeze: false,
        statusName: ""
    },
    {
        id: 15,
        name: "WXDi-D01-015[EN]",
        imageUrl: "/WXDi-D01/MAIN/WXDi-D01-015[EN].jpg",
        cardName: "",
        cardType: "SIGNI",
        cardColor: ["red"],
        cardText: "",
        cardEffectConst: "",
        cardEffectAuto: "Tự Động: Bất cứ khi nào SIGNI này tấn công, chọn một SIGNI khác trên sân của bạn để nhận được 5000 sức mạnh cho đến khi kết thúc lượt.",
        cardEffectEnter: "Vào Sân: Bỏ 2 lá bài, rút 2 lá bài.",
        cardEffectAction: "",
        cardLevel: 3,
        cardCost: 0,
        cardGrowCost: 0,
        cardLimit: 0,
        cardLRIGType: "",
        cardTeamName: "",
        cardClass: "War Tone: Armed",
        cardPower: 12000,
        cardBurst: "Chọn 1 trong 2 hiệu ứng: 1-Loại bỏ 1 SIGNI đã mở trên sân đối thủ. 2-Rút 1 lá bài.",
        cardUseTime: [""],
        isLRIGCenter: false,
        isLRIGSupport: false,
        cardEffect: ["Auto", "Enter"],
        isDown: false,
        isFreeze: false,
        statusName: ""
    },
    {
        id: 16,
        name: "WXDi-D01-016[EN]",
        imageUrl: "/WXDi-D01/MAIN/WXDi-D01-016[EN].jpg",
        cardName: "",
        cardType: "SIGNI",
        cardColor: ["blue"],
        cardText: "",
        cardEffectConst: "",
        cardEffectAuto: "Tự Động: Bất cứ khi nào SIGNI này tấn công, nếu sức mạnh của nó từ 15000 trở lên, đối thủ của bạn sẽ loại bỏ một lá bài. Nếu sức mạnh của nó là 20000 trở lên, đối thủ của bạn thay vào đó sẽ loại bỏ một lá bài ngẫu nhiên.",
        cardEffectEnter: "",
        cardEffectAction: "",
        cardLevel: 3,
        cardCost: 0,
        cardGrowCost: 0,
        cardLimit: 0,
        cardLRIGType: "",
        cardTeamName: "",
        cardClass: "Nature Tone: Jewel",
        cardPower: 12000,
        cardBurst: "Hạ 1 SIGNI trên sân đối thủ và đóng băng nó. Rút 1 lá bài.",
        cardUseTime: [""],
        isLRIGCenter: false,
        isLRIGSupport: false,
        cardEffect: ["Auto"],
        isDown: false,
        isFreeze: false,
        statusName: ""
    },
    {
        id: 17,
        name: "WXDi-D01-017[EN]",
        imageUrl: "/WXDi-D01/MAIN/WXDi-D01-017[EN].jpg",
        cardName: "",
        cardType: "SIGNI",
        cardColor: ["green"],
        cardText: "",
        cardEffectConst: "",
        cardEffectAuto: "",
        cardEffectEnter: "Vào Sân: Chọn ba SIGNI với các lớp khác nhau từ Vùng nguyên liệu của bạn vào thùng rác của bạn: Loại bỏ 1 SIGNI trên sân của đối thủ với sức mạnh từ 8000 trở lên.",
        cardEffectAction: "",
        cardLevel: 3,
        cardCost: 0,
        cardGrowCost: 0,
        cardLimit: 0,
        cardLRIGType: "",
        cardTeamName: "",
        cardClass: "Idol Tone: Angel",
        cardPower: 12000,
        cardBurst: "",
        cardUseTime: [""],
        isLRIGCenter: false,
        isLRIGSupport: false,
        cardEffect: ["Enter"],
        isDown: false,
        isFreeze: false,
        statusName: ""
    },
    {
        id: 18,
        name: "WXDi-D01-018[EN]",
        imageUrl: "/WXDi-D01/MAIN/WXDi-D01-018[EN].jpg",
        cardName: "",
        cardType: "SIGNI",
        cardColor: ["blue", "green"],
        cardText: "",
        cardEffectConst: "",
        cardEffectAuto: "",
        cardEffectEnter: "",
        cardEffectAction: "",
        cardLevel: 1,
        cardCost: 0,
        cardGrowCost: 0,
        cardLimit: 0,
        cardLRIGType: "",
        cardTeamName: "",
        cardClass: "Living Tone: Aquatic Beast",
        cardPower: 5000,
        cardBurst: "",
        cardUseTime: [""],
        isLRIGCenter: false,
        isLRIGSupport: false,
        cardEffect: [""],
        isDown: false,
        isFreeze: false,
        statusName: ""
    },
    {
        id: 19,
        name: "WXDi-D01-019[EN]",
        imageUrl: "/WXDi-D01/MAIN/WXDi-D01-019[EN].jpg",
        cardName: "",
        cardType: "SIGNI",
        cardColor: ["red", "green"],
        cardText: "",
        cardEffectConst: "",
        cardEffectAuto: "",
        cardEffectEnter: "",
        cardEffectAction: "",
        cardLevel: 2,
        cardCost: 0,
        cardGrowCost: 0,
        cardLimit: 0,
        cardLRIGType: "",
        cardTeamName: "",
        cardClass: "Living Tone: Terra Beast",
        cardPower: 10000,
        cardBurst: "",
        cardUseTime: [""],
        isLRIGCenter: false,
        isLRIGSupport: false,
        cardEffect: [""],
        isDown: false,
        isFreeze: false,
        statusName: ""
    },
    {
        id: 20,
        name: "WXDi-D01-020[EN]",
        imageUrl: "/WXDi-D01/MAIN/WXDi-D01-020[EN].jpg",
        cardName: "",
        cardType: "Guard",
        cardColor: ["blue", "red", "green", "white", "black"],
        cardText: "",
        cardEffectConst: "",
        cardEffectAuto: "",
        cardEffectEnter: "",
        cardEffectAction: "",
        cardLevel: 1,
        cardCost: 0,
        cardGrowCost: 0,
        cardLimit: 0,
        cardLRIGType: "",
        cardTeamName: "",
        cardClass: "Primal Tone",
        cardPower: 1000,
        cardBurst: "Chọn 1 SIGNI từ thùng rác lên tay.",
        cardUseTime: [""],
        isLRIGCenter: false,
        isLRIGSupport: false,
        cardEffect: [""],
        isDown: false,
        isFreeze: false,
        statusName: ""
    },
    {
        id: 21,
        name: "WXDi-D01-021[EN]",
        imageUrl: "/WXDi-D01/MAIN/WXDi-D01-021[EN].jpg",
        cardName: "",
        cardType: "SPELL",
        cardColor: ["green"],
        cardText: "Lấy 1 SIGNI màu xanh lá từ Vùng nguyên liệu vào tay bạn. Nếu có ba LRIG thuộc nhóm <Ancient Surprise> trên sân của bạn, thay vào đó hãy lấy 1 SIGNI bất kỳ từ Vùng nguyên liệu vào tay bạn.",
        cardEffectConst: "",
        cardEffectAuto: "",
        cardEffectEnter: "",
        cardEffectAction: "",
        cardLevel: 0,
        cardCost: 1,
        cardGrowCost: 0,
        cardLimit: 0,
        cardLRIGType: "",
        cardTeamName: "",
        cardClass: "",
        cardPower: 0,
        cardBurst: "Loại bỏ 1 SIGNI đã mở trên sân của đối thủ.",
        cardUseTime: [""],
        isLRIGCenter: false,
        isLRIGSupport: false,
        cardEffect: [""],
        isDown: false,
        isFreeze: false,
        statusName: ""
    }
];

export default cardList;