import Card from "../types/cardList";

const cardList: Card[] = [
    {
        id: -1,
        name: 'MAINbackside',
        imageUrl: '/backside/MAIN.jpg',
        cardName: "backsideMAIN",
        cardType: "",
        cardColor: "",
        cardText: "",
        cardLevel: 0,
        cardCost: 0,
        cardGrowCost: 0,
        cardLimit: 0,
        cardLRIGType: "",
        cardTeamName: "",
        cardClass: "",
        cardPower: 0,
        cardBurst: "",
        cardUseTime: "",
    },
    {
        id: 0,
        name: 'LRIGbackside',
        imageUrl: '/backside/LRIG.jpg',
        cardName: "backsideLRIG",
        cardType: "",
        cardColor: "",
        cardText: "",
        cardLevel: 0,
        cardCost: 0,
        cardGrowCost: 0,
        cardLimit: 0,
        cardLRIGType: "",
        cardTeamName: "",
        cardClass: "",
        cardPower: 0,
        cardBurst: "",
        cardUseTime: "",
    },
    {
        id: 1,
        name: 'WXDi-D01-001[EN]',
        imageUrl: '/WXDi-D01/LRIG/WXDi-D01-001[EN].jpg',
        cardName: "At =Noll=, the Opened Gate",
        cardType: "LRIG",
        cardColor: "green",
        cardText: "",
        cardLevel: 0,
        cardCost: 0,
        cardGrowCost: 0,
        cardLimit: 0,
        cardLRIGType: "A t",
        cardTeamName: "???",
        cardClass: "",
        cardPower: 0,
        cardBurst: "",
        cardUseTime: "",
    },
    {
        id: 2,
        name: 'WXDi-D01-002[EN]',
        imageUrl: '/WXDi-D01/LRIG/WXDi-D01-002[EN].jpg',
        cardName: "At =Ett=, the Opened Gate",
        cardType: "LRIG",
        cardColor: "green",
        cardText: "",
        cardLevel: 1,
        cardCost: 0,
        cardGrowCost: 0,
        cardLimit: 2,
        cardLRIGType: "A t",
        cardTeamName: "???",
        cardClass: "",
        cardPower: 0,
        cardBurst: "",
        cardUseTime: "",
    },
    {
        id: 3,
        name: 'WXDi-D01-003[EN]',
        imageUrl: '/WXDi-D01/LRIG/WXDi-D01-003[EN].jpg',
        cardName: "At =Tva=, the Opened Gate",
        cardType: "LRIG",
        cardColor: "green",
        cardText: "",
        cardLevel: 2,
        cardCost: 0,
        cardGrowCost: 1,
        cardLimit: 5,
        cardLRIGType: "A t",
        cardTeamName: "???",
        cardClass: "",
        cardPower: 0,
        cardBurst: "",
        cardUseTime: "",
    },
    {
        id: 4,
        name: 'WXDi-D01-004[EN]',
        imageUrl: '/WXDi-D01/LRIG/WXDi-D01-004[EN].jpg',
        cardName: "At =Tre=, the Opened Gate",
        cardType: "LRIG",
        cardColor: "green",
        cardText: "",
        cardLevel: 3,
        cardCost: 0,
        cardGrowCost: 2,
        cardLimit: 6,
        cardLRIGType: "A t",
        cardTeamName: "???",
        cardClass: "",
        cardPower: 0,
        cardBurst: "",
        cardUseTime: "",
    },
    {
        id: 5,
        name: 'WXDi-D01-005[EN]',
        imageUrl: '/WXDi-D01/LRIG/WXDi-D01-005[EN].jpg',
        cardName: "",
        cardType: "",
        cardColor: "",
        cardText: "",
        cardLevel: 0,
        cardCost: 0,
        cardGrowCost: 0,
        cardLimit: 0,
        cardLRIGType: "",
        cardTeamName: "",
        cardClass: "",
        cardPower: 0,
        cardBurst: "",
        cardUseTime: "",
    },
    {
        id: 6,
        name: 'WXDi-D01-006[EN]',
        imageUrl: '/WXDi-D01/LRIG/WXDi-D01-006[EN].jpg',
        cardName: "",
        cardType: "",
        cardColor: "",
        cardText: "",
        cardLevel: 0,
        cardCost: 0,
        cardGrowCost: 0,
        cardLimit: 0,
        cardLRIGType: "",
        cardTeamName: "",
        cardClass: "",
        cardPower: 0,
        cardBurst: "",
        cardUseTime: "",
    },
    {
        id: 7,
        name: 'WXDi-D01-007[EN]',
        imageUrl: '/WXDi-D01/LRIG/WXDi-D01-007[EN].jpg',
        cardName: "",
        cardType: "",
        cardColor: "",
        cardText: "",
        cardLevel: 0,
        cardCost: 0,
        cardGrowCost: 0,
        cardLimit: 0,
        cardLRIGType: "",
        cardTeamName: "",
        cardClass: "",
        cardPower: 0,
        cardBurst: "",
        cardUseTime: "",
    },
    {
        id: 8,
        name: 'WXDi-D01-008[EN]',
        imageUrl: '/WXDi-D01/LRIG/WXDi-D01-008[EN].jpg',
        cardName: "",
        cardType: "",
        cardColor: "",
        cardText: "",
        cardLevel: 0,
        cardCost: 0,
        cardGrowCost: 0,
        cardLimit: 0,
        cardLRIGType: "",
        cardTeamName: "",
        cardClass: "",
        cardPower: 0,
        cardBurst: "",
        cardUseTime: "",
    },
    {
        id: 9,
        name: 'WXDi-D01-009[EN]',
        imageUrl: '/WXDi-D01/LRIG/WXDi-D01-009[EN].jpg',
        cardName: "",
        cardType: "",
        cardColor: "",
        cardText: "",
        cardLevel: 0,
        cardCost: 0,
        cardGrowCost: 0,
        cardLimit: 0,
        cardLRIGType: "",
        cardTeamName: "",
        cardClass: "",
        cardPower: 0,
        cardBurst: "",
        cardUseTime: "",
    },
    {
        id: 10,
        name: 'WXDi-D01-010[EN]',
        imageUrl: '/WXDi-D01/LRIG/WXDi-D01-010[EN].jpg',
        cardName: "",
        cardType: "",
        cardColor: "",
        cardText: "",
        cardLevel: 0,
        cardCost: 0,
        cardGrowCost: 0,
        cardLimit: 0,
        cardLRIGType: "",
        cardTeamName: "",
        cardClass: "",
        cardPower: 0,
        cardBurst: "",
        cardUseTime: "",
    },
    {
        id: 11,
        name: 'WXDi-D01-011[EN]',
        imageUrl: '/WXDi-D01/LRIG/WXDi-D01-011[EN].jpg',
        cardName: "",
        cardType: "",
        cardColor: "",
        cardText: "",
        cardLevel: 0,
        cardCost: 0,
        cardGrowCost: 0,
        cardLimit: 0,
        cardLRIGType: "",
        cardTeamName: "",
        cardClass: "",
        cardPower: 0,
        cardBurst: "",
        cardUseTime: "",
    },
];

export default cardList;