import Card from "../types/cardList";

const cardList: Card[] = [
    {
        id: -1,
        name: 'MAINbackside',
        imageUrl: '/backside/MAIN.jpg',
        cardName: "backsideMAIN",
        cardType: "",
        cardColor: "",
        cardText: "",
        cardLevel: 0,
        cardCost: 0,
        cardGrowCost: 0,
        cardLimit: 0,
        cardLRIGType: "",
        cardTeamName: "",
        cardClass: "",
        cardPower: 0,
        cardBurst: "",
        cardUseTime: "",
        isLRIGCenter: false,
        isLRIGSupport: false
    },
    {
        id: 0,
        name: 'LRIGbackside',
        imageUrl: '/backside/LRIG.jpg',
        cardName: "backsideLRIG",
        cardType: "",
        cardColor: "",
        cardText: "",
        cardLevel: 0,
        cardCost: 0,
        cardGrowCost: 0,
        cardLimit: 0,
        cardLRIGType: "",
        cardTeamName: "",
        cardClass: "",
        cardPower: 0,
        cardBurst: "",
        cardUseTime: "",
        isLRIGCenter: false,
        isLRIGSupport: false
    },
    {
        id: 1,
        name: 'WXDi-D01-001[EN]',
        imageUrl: '/WXDi-D01/LRIG/WXDi-D01-001[EN].jpg',
        cardName: "At =Noll=, the Opened Gate",
        cardType: "LRIG",
        cardColor: "green",
        cardText: "",
        cardLevel: 0,
        cardCost: 0,
        cardGrowCost: 0,
        cardLimit: 0,
        cardLRIGType: "A t",
        cardTeamName: "???",
        cardClass: "",
        cardPower: 0,
        cardBurst: "",
        cardUseTime: "",
        isLRIGCenter: true,
        isLRIGSupport: false
    },
    {
        id: 2,
        name: 'WXDi-D01-002[EN]',
        imageUrl: '/WXDi-D01/LRIG/WXDi-D01-002[EN].jpg',
        cardName: "At =Ett=, the Opened Gate",
        cardType: "LRIG",
        cardColor: "green",
        cardText: "",
        cardLevel: 1,
        cardCost: 0,
        cardGrowCost: 0,
        cardLimit: 2,
        cardLRIGType: "A t",
        cardTeamName: "???",
        cardClass: "",
        cardPower: 0,
        cardBurst: "",
        cardUseTime: "",
        isLRIGCenter: true,
        isLRIGSupport: false
    },
    {
        id: 3,
        name: 'WXDi-D01-003[EN]',
        imageUrl: '/WXDi-D01/LRIG/WXDi-D01-003[EN].jpg',
        cardName: "At =Tva=, the Opened Gate",
        cardType: "LRIG",
        cardColor: "green",
        cardText: "",
        cardLevel: 2,
        cardCost: 0,
        cardGrowCost: 1,
        cardLimit: 5,
        cardLRIGType: "A t",
        cardTeamName: "???",
        cardClass: "",
        cardPower: 0,
        cardBurst: "",
        cardUseTime: "",
        isLRIGCenter: true,
        isLRIGSupport: false
    },
    {
        id: 4,
        name: 'WXDi-D01-004[EN]',
        imageUrl: '/WXDi-D01/LRIG/WXDi-D01-004[EN].jpg',
        cardName: "At =Tre=, the Opened Gate",
        cardType: "LRIG",
        cardColor: "green",
        cardText: "",
        cardLevel: 3,
        cardCost: 0,
        cardGrowCost: 2,
        cardLimit: 6,
        cardLRIGType: "A t",
        cardTeamName: "???",
        cardClass: "",
        cardPower: 0,
        cardBurst: "",
        cardUseTime: "",
        isLRIGCenter: true,
        isLRIGSupport: false
    },
    {
        id: 5,
        name: 'WXDi-D01-005[EN]',
        imageUrl: '/WXDi-D01/LRIG/WXDi-D01-005[EN].jpg',
        cardName: "",
        cardType: "",
        cardColor: "",
        cardText: "",
        cardLevel: 0,
        cardCost: 0,
        cardGrowCost: 0,
        cardLimit: 0,
        cardLRIGType: "",
        cardTeamName: "",
        cardClass: "",
        cardPower: 0,
        cardBurst: "",
        cardUseTime: "",
        isLRIGCenter: false,
        isLRIGSupport: true
    },
    {
        id: 6,
        name: 'WXDi-D01-006[EN]',
        imageUrl: '/WXDi-D01/LRIG/WXDi-D01-006[EN].jpg',
        cardName: "",
        cardType: "",
        cardColor: "",
        cardText: "",
        cardLevel: 1,
        cardCost: 0,
        cardGrowCost: 0,
        cardLimit: 0,
        cardLRIGType: "",
        cardTeamName: "",
        cardClass: "",
        cardPower: 0,
        cardBurst: "",
        cardUseTime: "",
        isLRIGCenter: false,
        isLRIGSupport: true
    },
    {
        id: 7,
        name: 'WXDi-D01-007[EN]',
        imageUrl: '/WXDi-D01/LRIG/WXDi-D01-007[EN].jpg',
        cardName: "",
        cardType: "",
        cardColor: "",
        cardText: "",
        cardLevel: 2,
        cardCost: 0,
        cardGrowCost: 0,
        cardLimit: 0,
        cardLRIGType: "",
        cardTeamName: "",
        cardClass: "",
        cardPower: 0,
        cardBurst: "",
        cardUseTime: "",
        isLRIGCenter: false,
        isLRIGSupport: true
    },
    {
        id: 8,
        name: 'WXDi-D01-008[EN]',
        imageUrl: '/WXDi-D01/LRIG/WXDi-D01-008[EN].jpg',
        cardName: "",
        cardType: "",
        cardColor: "",
        cardText: "",
        cardLevel: 0,
        cardCost: 0,
        cardGrowCost: 0,
        cardLimit: 0,
        cardLRIGType: "",
        cardTeamName: "",
        cardClass: "",
        cardPower: 0,
        cardBurst: "",
        cardUseTime: "",
        isLRIGCenter: false,
        isLRIGSupport: true
    },
    {
        id: 9,
        name: 'WXDi-D01-009[EN]',
        imageUrl: '/WXDi-D01/LRIG/WXDi-D01-009[EN].jpg',
        cardName: "",
        cardType: "",
        cardColor: "",
        cardText: "",
        cardLevel: 1,
        cardCost: 0,
        cardGrowCost: 0,
        cardLimit: 0,
        cardLRIGType: "",
        cardTeamName: "",
        cardClass: "",
        cardPower: 0,
        cardBurst: "",
        cardUseTime: "",
        isLRIGCenter: false,
        isLRIGSupport: true
    },
    {
        id: 10,
        name: 'WXDi-D01-010[EN]',
        imageUrl: '/WXDi-D01/LRIG/WXDi-D01-010[EN].jpg',
        cardName: "",
        cardType: "",
        cardColor: "",
        cardText: "",
        cardLevel: 2,
        cardCost: 0,
        cardGrowCost: 0,
        cardLimit: 0,
        cardLRIGType: "",
        cardTeamName: "",
        cardClass: "",
        cardPower: 0,
        cardBurst: "",
        cardUseTime: "",
        isLRIGCenter: false,
        isLRIGSupport: true
    },
    {
        id: 11,
        name: 'WXDi-D01-011[EN]',
        imageUrl: '/WXDi-D01/LRIG/WXDi-D01-011[EN].jpg',
        cardName: "",
        cardType: "",
        cardColor: "",
        cardText: "",
        cardLevel: 0,
        cardCost: 0,
        cardGrowCost: 0,
        cardLimit: 0,
        cardLRIGType: "",
        cardTeamName: "",
        cardClass: "",
        cardPower: 0,
        cardBurst: "",
        cardUseTime: "",
        isLRIGCenter: false,
        isLRIGSupport: false
    },
    {
        id: 12,
        name: "WXDi-D01-012[EN]",
        imageUrl: "/WXDi-D01/MAIN/WXDi-D01-012[EN].jpg",
        cardName: "",
        cardType: "",
        cardColor: "",
        cardText: "",
        cardLevel: 0,
        cardCost: 0,
        cardGrowCost: 0,
        cardLimit: 0,
        cardLRIGType: "",
        cardTeamName: "",
        cardClass: "",
        cardPower: 0,
        cardBurst: "",
        cardUseTime: "",
        isLRIGCenter: false,
        isLRIGSupport: false
    },
    {
        id: 13,
        name: "WXDi-D01-013[EN]",
        imageUrl: "/WXDi-D01/MAIN/WXDi-D01-013[EN].jpg",
        cardName: "",
        cardType: "",
        cardColor: "",
        cardText: "",
        cardLevel: 0,
        cardCost: 0,
        cardGrowCost: 0,
        cardLimit: 0,
        cardLRIGType: "",
        cardTeamName: "",
        cardClass: "",
        cardPower: 0,
        cardBurst: "",
        cardUseTime: "",
        isLRIGCenter: false,
        isLRIGSupport: false
    },
    {
        id: 14,
        name: "WXDi-D01-014[EN]",
        imageUrl: "/WXDi-D01/MAIN/WXDi-D01-014[EN].jpg",
        cardName: "",
        cardType: "",
        cardColor: "",
        cardText: "",
        cardLevel: 0,
        cardCost: 0,
        cardGrowCost: 0,
        cardLimit: 0,
        cardLRIGType: "",
        cardTeamName: "",
        cardClass: "",
        cardPower: 0,
        cardBurst: "",
        cardUseTime: "",
        isLRIGCenter: false,
        isLRIGSupport: false
    },
    {
        id: 15,
        name: "WXDi-D01-015[EN]",
        imageUrl: "/WXDi-D01/MAIN/WXDi-D01-015[EN].jpg",
        cardName: "",
        cardType: "",
        cardColor: "",
        cardText: "",
        cardLevel: 0,
        cardCost: 0,
        cardGrowCost: 0,
        cardLimit: 0,
        cardLRIGType: "",
        cardTeamName: "",
        cardClass: "",
        cardPower: 0,
        cardBurst: "",
        cardUseTime: "",
        isLRIGCenter: false,
        isLRIGSupport: false
    },
    {
        id: 16,
        name: "WXDi-D01-016[EN]",
        imageUrl: "/WXDi-D01/MAIN/WXDi-D01-016[EN].jpg",
        cardName: "",
        cardType: "",
        cardColor: "",
        cardText: "",
        cardLevel: 0,
        cardCost: 0,
        cardGrowCost: 0,
        cardLimit: 0,
        cardLRIGType: "",
        cardTeamName: "",
        cardClass: "",
        cardPower: 0,
        cardBurst: "",
        cardUseTime: "",
        isLRIGCenter: false,
        isLRIGSupport: false
    },
    {
        id: 17,
        name: "WXDi-D01-017[EN]",
        imageUrl: "/WXDi-D01/MAIN/WXDi-D01-017[EN].jpg",
        cardName: "",
        cardType: "",
        cardColor: "",
        cardText: "",
        cardLevel: 0,
        cardCost: 0,
        cardGrowCost: 0,
        cardLimit: 0,
        cardLRIGType: "",
        cardTeamName: "",
        cardClass: "",
        cardPower: 0,
        cardBurst: "",
        cardUseTime: "",
        isLRIGCenter: false,
        isLRIGSupport: false
    },
    {
        id: 18,
        name: "WXDi-D01-018[EN]",
        imageUrl: "/WXDi-D01/MAIN/WXDi-D01-018[EN].jpg",
        cardName: "",
        cardType: "",
        cardColor: "",
        cardText: "",
        cardLevel: 0,
        cardCost: 0,
        cardGrowCost: 0,
        cardLimit: 0,
        cardLRIGType: "",
        cardTeamName: "",
        cardClass: "",
        cardPower: 0,
        cardBurst: "",
        cardUseTime: "",
        isLRIGCenter: false,
        isLRIGSupport: false
    },
    {
        id: 19,
        name: "WXDi-D01-019[EN]",
        imageUrl: "/WXDi-D01/MAIN/WXDi-D01-019[EN].jpg",
        cardName: "",
        cardType: "",
        cardColor: "",
        cardText: "",
        cardLevel: 0,
        cardCost: 0,
        cardGrowCost: 0,
        cardLimit: 0,
        cardLRIGType: "",
        cardTeamName: "",
        cardClass: "",
        cardPower: 0,
        cardBurst: "",
        cardUseTime: "",
        isLRIGCenter: false,
        isLRIGSupport: false
    },
    {
        id: 20,
        name: "WXDi-D01-020[EN]",
        imageUrl: "/WXDi-D01/MAIN/WXDi-D01-020[EN].jpg",
        cardName: "",
        cardType: "",
        cardColor: "",
        cardText: "",
        cardLevel: 0,
        cardCost: 0,
        cardGrowCost: 0,
        cardLimit: 0,
        cardLRIGType: "",
        cardTeamName: "",
        cardClass: "",
        cardPower: 0,
        cardBurst: "",
        cardUseTime: "",
        isLRIGCenter: false,
        isLRIGSupport: false
    },
    {
        id: 21,
        name: "WXDi-D01-021[EN]",
        imageUrl: "/WXDi-D01/MAIN/WXDi-D01-021[EN].jpg",
        cardName: "",
        cardType: "",
        cardColor: "",
        cardText: "",
        cardLevel: 0,
        cardCost: 0,
        cardGrowCost: 0,
        cardLimit: 0,
        cardLRIGType: "",
        cardTeamName: "",
        cardClass: "",
        cardPower: 0,
        cardBurst: "",
        cardUseTime: "",
        isLRIGCenter: false,
        isLRIGSupport: false
    }
];

export default cardList;